display_options:
  config_names:
    global_hash_table: Global Hash Table
    radix_trees: Radix Trees
    extent_trees: Extent Trees
    level_hash_tables: Level Hash Tables

  config_colors:
    Global Hash Table: '#a8ddb5'
    Radix Trees: '#7bccc4'
    Extent Trees: '#fed98e'
    Level Hash Tables: '#ff0044'

  config_order:
    - Global Hash Table
    - Radix Trees
    - Extent Trees
    - Level Hash Tables

